#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

//#define UIP_CONF_BUFFER_SIZE 500
#define COAP_MAX_CHUNK_SIZE 200
#define COAP_MAX_OPEN_TRANSACTIONS 6

#define LOG_ENABLED false

#endif /* PROJECT_CONF_H_ */
