{
 "title": "smart agriculture dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 } },
  {
   "title": "Percentage of Violation per Land and Sensor",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  v_type,\n  V.violations/M.measurements\nFROM (SELECT \n    CONCAT(\"land_\",CAST(land_id AS CHAR(100)), \"-\", sensor) AS v_type,\n    COUNT(*) AS violations \n  FROM violation \n  GROUP BY land_id, sensor\n  ) AS V INNER JOIN \n  (SELECT \n    CONCAT(\"land_\",CAST(land_id AS CHAR(100)), \"-\", sensor) AS m_type,\n    COUNT(*) AS measurements \n  FROM measurement \n  GROUP BY land_id, sensor\n  ) AS M\n  ON v_type=m_type\nORDER BY v_type"
    }
   ]
  },
  {
   "title": "Ph Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 1\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'ph' AND land_id = 1\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 2\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'ph' AND land_id = 2\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 3\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'ph' AND land_id = 3\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 4\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'ph' AND land_id = 4\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 5\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'ph' AND land_id = 5\nORDER BY m_timestamp"
    }
   ]
  },
  {
   "title": "Soil Temperature Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 1\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'tmp' AND land_id = 1\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 2\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'tmp' AND land_id = 2\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 3\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'tmp' AND land_id = 3\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 4\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'tmp' AND land_id = 4\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 5\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'tmp' AND land_id = 5\nORDER BY m_timestamp"
    }
   ]
  },
  {
   "title": "Moisture Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 1\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'moisture' AND land_id = 1\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 2\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'moisture' AND land_id = 2\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 3\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'moisture' AND land_id = 3\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 4\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'moisture' AND land_id = 4\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 5\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'moisture' AND land_id = 5\nORDER BY m_timestamp"
    }
   ]
  },
  {
   "title": "Light Ray Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 1\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'light' AND land_id = 1\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 2\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'light' AND land_id = 2\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 3\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'light' AND land_id = 3\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 4\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'light' AND land_id = 4\nORDER BY m_timestamp"
    },
    {
     "rawSql": "SELECT\n  m_timestamp AS \"time\",\n  m_value AS \"land 5\"\nFROM measurement\nWHERE\n  $__timeFilter(m_timestamp) AND sensor = 'light' AND land_id = 5\nORDER BY m_timestamp"
    }
   ]
  },
  {
   "title": "AVG Soil Temperature per Land",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  land_id as land,\n  AVG(m_value) as avg_soil_temperature,\n  land.min_tmp as min_bound,\n  land.max_tmp as max_bound\nFROM measurement INNER JOIN land ON measurement.land_id=land.id\nWHERE sensor = 'tmp'\nGROUP BY land_id"
    }
   ]
  },
  {
   "title": "AVG Ph per Land",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  land_id as land,\n  AVG(m_value) as avg_ph,\n  land.min_ph as min_bound,\n  land.max_ph as max_bound\nFROM measurement INNER JOIN land ON measurement.land_id=land.id\nWHERE sensor = 'ph'\nGROUP BY land_id"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONCAT(\"NODE/\", CAST(land_id AS CHAR(100)), \"/\", CAST(node_id AS CHAR(100))) as node,\n  status,\n  last_timestamp as timestamp\nFROM configuration\nWHERE node_id <> 0\nORDER BY status DESC"
    }
   ]
  },
  {
   "title": "AVG Moisture per Land",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n  land_id as land,\n  AVG(m_value) as avg_moisture,\n  land.mst_trashold as trashold\nFROM measurement INNER JOIN land ON measurement.land_id=land.id\nWHERE sensor = 'moisture'\nGROUP BY land_id"
    }
   ]
  },
  {
   "title": "Configurations",
   "type": "table",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT \n  CONCAT(\"NODE/\", CAST(land_id AS CHAR(100)), \"/\", CAST(node_id AS CHAR(100))) as node,\n  protocol,\n  address,\n  irr_enabled,\n  irr_limit,\n  irr_duration,\n  mst_timer,\n  ph_timer,\n  light_timer,\n  tmp_timer\nFROM configuration\nWHERE node_id <> 0"
    }
   ]
  },
  {
   "title": "Lands",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "targets": [
    { "rawSql": "SELECT *\nFROM land\n" }
   ]
  }
 ]
}